[package]
name = "duckmomma"
version = "0.1.0"
authors = ["dosmoc <dcesebiond@gmail.com>"]

[[bin]]
name = "duckmomma"

[dependencies]
piston = "0.31.4"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.35.0"
piston2d-opengl_graphics = "0.42.1"
num = "0.1.37"
