[package]
name = "duckmomma"
version = "0.1.0"
authors = ["dosmoc <dcesebiond@gmail.com>"]

[[bin]]
name = "duckmomma"

[dependencies]
piston = "0.25.1"
piston2d-graphics = "0.17.0"
pistoncore-glutin_window = "0.30.0"
piston2d-opengl_graphics = "0.33.0"
num = "0.1.36"
